import "../_styles/globals.css";

import { ToastProvider } from "../_components/client";
import { TanstackProvider } from "./_components";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "뚜두뚜두",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ko">
      <body>
        <TanstackProvider>
          <main id="app">
            <ToastProvider>{children}</ToastProvider>
          </main>
        </TanstackProvider>
      </body>
    </html>
  );
};

export default RootLayout;
