import "../_styles/globals.css";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "뚜두뚜두",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ko">
      <body>
        <main id="app">{children}</main>
      </body>
    </html>
  );
};

export default RootLayout;
